# ZTM TensorFlow Developer
### Exercise 00: TensorfFlow Fundamentals

---

# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [1]:
# get libraries
import tensorflow as tf
import numpy as np

tf.__version__

'2.8.0'

In [2]:
scalar = tf.constant(0)
scalar

Metal device set to: Apple M1


2022-02-24 23:11:02.240867: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-02-24 23:11:02.241241: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [3]:
vector = tf.constant([0, 0])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0], dtype=int32)>

In [4]:
matrix = tf.constant(
    [[0, 0],
     [0, 0],
     [0, 0]]
)
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [5]:
tensor = tf.constant(
    [[[0, 0, 0, 0],
      [0, 0, 0, 0]],
     [[0, 0, 0, 0],
      [0, 0, 0, 0]],
     [[0, 0, 0, 0],
      [0, 0, 0, 0]]]
)
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>