# Exercise 00: TensorfFlow Fundamentals

---

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [1]:
# get libraries
import tensorflow as tf
import numpy as np

tf.__version__

'2.8.0'

In [6]:
# 0 dimension scalar
scalar = tf.constant(0)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
# 1 dimension vector
vector = tf.constant([0, 0])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0], dtype=int32)>

In [8]:
# 2 dimension matrix
matrix = tf.constant(
    [[0, 0],
     [0, 0],
     [0, 0]]
)
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [9]:
# 3 dimension matrix
tensor = tf.constant(
    [[[0, 0, 0, 0],
      [0, 0, 0, 0]],
     [[0, 0, 0, 0],
      [0, 0, 0, 0]],
     [[0, 0, 0, 0],
      [0, 0, 0, 0]]]
)
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

---

## 2. Find the shape, rank and size of the tensors you created in 1.

In [10]:
# get shape of scalar
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [11]:
# get shape of vector
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [12]:
# get shape of matrix
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([3, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [13]:
# get shape of tensor
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([3, 2, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

---

## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [14]:
# first tensor
A = tf.random.uniform(
    shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.float32,
    seed=420
)
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.00758517, 0.01840913, 0.74574125, ..., 0.7917652 , 0.71933794,
        0.6644155 ],
       [0.33537483, 0.22464633, 0.22402322, ..., 0.98940337, 0.5123824 ,
        0.42909515],
       [0.871809  , 0.00421321, 0.2560923 , ..., 0.59744895, 0.8133625 ,
        0.7780876 ],
       [0.09770846, 0.5519749 , 0.8556391 , ..., 0.17689979, 0.43587124,
        0.6857778 ],
       [0.71909857, 0.33022475, 0.80964684, ..., 0.38716078, 0.47679496,
        0.00854909]], dtype=float32)>

In [15]:
# second tensor
B = tf.random.uniform(
    shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.float32,
    seed=69
)
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.2713381 , 0.387509  , 0.33636308, ..., 0.11781955, 0.6478585 ,
        0.53925395],
       [0.7738329 , 0.5652894 , 0.5613414 , ..., 0.7031143 , 0.40229523,
        0.01156569],
       [0.05065179, 0.3228966 , 0.19899285, ..., 0.06214762, 0.9176872 ,
        0.69228125],
       [0.7523886 , 0.7231908 , 0.4190452 , ..., 0.7855053 , 0.70502317,
        0.28151345],
       [0.18620896, 0.32951486, 0.09288383, ..., 0.48747385, 0.4787408 ,
        0.16164422]], dtype=float32)>

---

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [16]:
# matmul
A @ tf.transpose(B)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.192444, 77.33469 , 75.70937 , 78.68404 , 79.19371 ],
       [72.63643 , 73.69871 , 67.59978 , 73.523315, 76.15776 ],
       [72.27921 , 71.6458  , 69.36307 , 73.17912 , 73.48836 ],
       [76.37137 , 75.03353 , 67.81703 , 75.502655, 75.1564  ],
       [71.52632 , 74.691345, 69.36871 , 76.79386 , 75.27805 ]],
      dtype=float32)>

---

## 5. Multiply the two tensors you created in 3 using dot product.

In [17]:
# dot product
tf.tensordot(A, tf.transpose(B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.192444, 77.33469 , 75.70937 , 78.68404 , 79.19371 ],
       [72.63643 , 73.69871 , 67.59978 , 73.523315, 76.15776 ],
       [72.27921 , 71.6458  , 69.36307 , 73.17912 , 73.48836 ],
       [76.37137 , 75.03353 , 67.81703 , 75.502655, 75.1564  ],
       [71.52632 , 74.691345, 69.36871 , 76.79386 , 75.27805 ]],
      dtype=float32)>

---

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [18]:
# create tensor
C = tf.random.normal([224, 224, 3])
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.10495866, -1.4683366 , -1.1347345 ],
        [ 0.2318989 , -1.8632584 ,  0.60235226],
        [-1.6730691 ,  0.05668333,  1.9255775 ],
        ...,
        [ 0.8079857 , -1.8614566 , -0.24877897],
        [-0.4811816 ,  0.32636225,  1.0801879 ],
        [-0.02307113,  0.6800442 ,  0.24893595]],

       [[ 1.5826645 ,  1.6053256 , -1.3522125 ],
        [ 1.801543  ,  0.18509354,  0.24776731],
        [-0.8665562 ,  1.2668227 ,  0.19387361],
        ...,
        [ 0.6186007 , -0.6692288 , -0.5830631 ],
        [ 0.5869385 , -0.4229871 ,  0.7259176 ],
        [-0.20144585,  0.49774268,  0.09687882]],

       [[ 1.2905781 , -0.443467  ,  0.3011403 ],
        [ 0.3505611 ,  0.4004034 , -1.1490575 ],
        [ 1.2047573 , -0.9306355 , -1.4924182 ],
        ...,
        [-1.2846395 ,  0.65174204, -0.01584451],
        [ 0.79439044, -0.23557337,  0.62322366],
        [ 0.14775348, -0.8353306 , -1.3252237 ]],

       ...,

     

---

## 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [19]:
# find min
C_min_1axis = tf.math.reduce_min(C)
C_min_1axis

<tf.Tensor: shape=(), dtype=float32, numpy=-4.2821026>

In [20]:
# find max
C_max_1axis = tf.math.reduce_max(C)
C_max_1axis

<tf.Tensor: shape=(), dtype=float32, numpy=4.3563757>

---

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [21]:
# create tensor
D = tf.random.normal([1, 224, 224, 3])
D.shape

TensorShape([1, 224, 224, 3])

In [22]:
# same tensor unsqueezed
D_squeezed = tf.squeeze(D)
D_squeezed.shape

TensorShape([224, 224, 3])

---

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [25]:
# create tensor
E = tf.random.normal([10])
E

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.7444058 ,  0.25791788, -0.15201972, -0.18569559,  0.84119457,
        1.474815  , -1.4047701 , -0.22256452, -0.13430586,  1.0699725 ],
      dtype=float32)>

In [26]:
# max value
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float32, numpy=1.474815>

In [27]:
# max value's position
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

---

## 10. One-hot encode the tensor you created in 9.

In [28]:
# one-hot the above tensor
tf.one_hot(
    indices=tf.cast(E, dtype=tf.int32).numpy(),
    depth=tf.size(E).numpy()
)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>