<a href="https://colab.research.google.com/github/hiydavid/tfdev_learning/blob/main/ZTM/notebooks/tfdev_00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00: TensorFlow Fundamentals

In this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow. More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

# Creating Tensors with `tf.constant()`

* `tf.constant()`: A method that creates immutable tf.Tensor object. 
* `tf.dtypes`: A module for data types used in TensorFlow. A full list can be found [here](https://www.tensorflow.org/api_docs/python/tf/dtypes)
* `tf.Tensor.ndim`: An attribute that check the dimension of a tf.Tensor object.

In [1]:
# import libraries
import numpy as np

import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

2022-02-24 23:33:43.203857: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-02-24 23:33:43.203956: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

Metal device set to: Apple M1


In [3]:
# check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant(
    [[10, 7], 
     [7, 10]]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# check the dimension of matrix
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant(
    [[10., 7.],
     [3. , 2.],
     [8. , 9.]],
     dtype=tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# check the dimension of matrix
another_matrix.ndim

2

In [10]:
# create a tensor
tensor = tf.constant(
    [[[1, 2, 3],
      [4, 5, 6]],
     [[7, 8, 9],
      [10, 11, 12]],
     [[13, 14, 15],
      [16, 17, 18]]]
)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# check tensor dimension
tensor.ndim

3

# Creating Tensors with `tf.Variable()`
* `tf.Variable()`: A method that creates mutable tf.Variable object
* `tf.Variable.assign()`: A method used to update a tf.Variable object.

In [12]:
# create the above tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# try changing the changeable_tensor using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# # now try changing the unchangeable_tensor using .assign()
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

# Creating Random Tensors

* `tf.random.Generator.from_seed(value)`: A class object that generate random numbers. The `from_seed()` method sets seed for reproducibility. Read about global seed vs. operation-level seed [here](https://www.tensorflow.org/api_docs/python/tf/random/set_seed).
* `tf.random.normal(shape=())`: A method that generates random numbers from a normal distribution. Other distribution can be found [here](https://www.tensorflow.org/api_docs/python/tf/random).
* `tf.random.shuffle(tf.Tensor)`: A method that takes a tf.Tensor object and shuffles the order along its first dimension.

In [16]:
# create two random tensors with the same seed
random_1 = tf.random.Generator.from_seed(42).normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3, 2))

random_1 == random_2

NotFoundError: No registered 'RngReadAndSkip' OpKernel for 'GPU' devices compatible with node {{node RngReadAndSkip}}
	.  Registered:  device='CPU'
 [Op:RngReadAndSkip]

In [ ]:
# shuffle the order of the elements in a tensor
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]]
)

tf.random.shuffle(not_shuffled)

In [ ]:
# shuffle with setting seed
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
# setting a global seed (now it no longer changes)
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

# Other Ways to Create Tensors

* `tf.ones(shape=())`: A method that creates a tensor with all 1s as elements.
* `tf.zeros(shape=())`: A method that creates a tensor with all 0s as elements.
* `tf.constant(np.arrange())`: Turn an numpy array into a tf.tensor.

In [ ]:
# create a tensor of 1s
tf.ones(shape=(3, 2))

In [ ]:
# create a tensor of all zeros
tf.zeros(shape=(9, 5))

In [ ]:
# create a tensor from numpy arrays
numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A)
numpy_A, A

In [ ]:
# create a tensor from numpy arrays
B = tf.constant(numpy_A, shape=(2, 4, 3)) # shape must match array length
C = tf.constant(numpy_A, shape=(3, 8))

B, C

# Getting Information from Tensors

* `tf.Tensor.shape`: A method that gets the shape of a tf.Tensor object.
* `tf.Tensor.ndim`: A method that gets the rank of a tf.Tensor object.
* `tf.Tensor[0]`: A way to get a particular axis of a tf.Tensor object.
* `tf.size(tf.Tensor)`: A method to get the total number of items in a tf.Tensor object.

In [ ]:
# create a rank 4 tensor
rank_4_tensor = tf.zeros([2, 3, 4, 5])
print("rank:", rank_4_tensor.ndim)
print("shape:", rank_4_tensor.shape)
print("size:", tf.size(rank_4_tensor).numpy())

In [ ]:
# other retreivable attributes of a tensor
print("datatype:", rank_4_tensor.dtype)
print("elements along the 0 axis:", rank_4_tensor.shape[0])
print("elements along last axis:", rank_4_tensor.shape[-1])

# Indexing Tensors

* `[:, :, :]`: Similar to how numpy is indexed.
* `[..., ]`: A way to say include everything that came before it.
* `tf.newaxis`: A NoneType that can be used to add as new element into an existing tf.Ternsor.
* `tf.expand_dims(tf.Tensor, axis)`: A method to add a dimension to an existing tf.Tensor.

In [ ]:
# get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# get the first element from each dimension from each index except final
rank_4_tensor[:1, :1, :1, ]

In [ ]:
# get the last item of each row of our rank 2 tensor
rank_2_tensor = tf.constant(
    [[10, 7], 
     [3, 4]]
)

rank_2_tensor[:, -1]

In [ ]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# alternative to using tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # expand the final axis

In [ ]:
# expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0) 

# Manipulating Tensors

* `+, -, *, /`: Operators works with each element in a tf.Tensor.
* `tf.multiply(tf.Tensor, value)`: Same as using the `*` operator. 
* `tf.math`: The modules that contains many of the commonly used operators

In [ ]:
# add values to a tensor using addition
tensor = tf.constant(
    [[10, 7], 
     [3, 4]]
)
tensor + 10

In [ ]:
# multiplication also works
tensor * 10

In [ ]:
# subtraction
tensor - 10

In [ ]:
# division
tensor / 2

In [ ]:
# we can use the tf built-in functions as well
tf.multiply(tensor, 10)

# Matrix Multiplication with Tensors

* `tf.matmult(tf.Tensor, tf.Tensor)`: Get dot product of two tf.Tensor objects.
* `@`: A python operator that's the same as tf.matmul.
* `tf.reshape(tf.Tensor, shape=())`: A method to transpose a tf.Tensor object. This is required to satisfy the matrix multiplication rule of matching inner dimensions of two different tensors.
* `tf.transpose(tf.Tensor)`: Also works, but this is flips the matrix by its diagonal axis, whereas reshape uses the same order but rebuilds the tensor into a new object.
* `tf.tensordot()`: This gets the dot product of two tf.Tensor objects. This method requires one of the two tf.Tensor objects to be transposed.
* Usually, transposing is the correct way in ML algorithms.

In [ ]:
# matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

In [ ]:
# matrix multiplication with Python operator "@"
tensor @ tensor

In [ ]:
# element-wise matrix multiplication
tensor * tensor

In [ ]:
# try with two tensors of different shapes
X = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6]]
)
Y = tf.constant(
    [[7, 8],
     [9, 10],
     [11, 12]]
)

# X @ Y # this gives you an error
X @ tf.transpose(Y)

In [ ]:
# reshape also works too
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
# however, transpose and reshape yields different resuls
Y, tf.transpose(Y), tf.reshape(Y, shape=(2, 3))

In [ ]:
# results are different
X @ tf.transpose(Y), X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
# use tensordot
tf.tensordot(X, tf.transpose(Y), axes=1)

# Changing the Datatype of a Tensor

* `tf.Tensor.dtype`: An attribute that looksup a tensor's data type.
* `tf.cast(tf.Tensor, dtype=)`: A method that changes a tensor's dtype.
* Sometimes it is good to have mixed precision (float16 & float32). Read more [here](https://www.tensorflow.org/guide/mixed_precision).

In [ ]:
# create a new tensor with default dtype (float32)
B = tf.constant(
    [1.7, 7.4]
)
B.dtype

In [ ]:
# create a new tensor with default detype (int32)
C = tf.constant(
    [7, 10]
)
C.dtype

In [ ]:
# change from float32 to float 16 (reducing precision)
D = tf.cast(B, dtype=tf.float16)
D.dtype

# Tensor Aggregation

* `tf.abs(tf.Tensor)`: A method that turns value into its absolute value.
* `tf.reduce_min(tf.Tensor)`: A method that gets the min value of a tensor.
* `tf.reduce_max(tf.Tensor)`: A method that gets the max value of a tensor.
* `tf.reduce_mean(tf.Tensor)`: A method that gets the mean of a tensor.
* `tf.reduce_sum(tf.Tensor)`: A method that gets the sum of a tensor.
* `tf.math.reduce_variance(tf.Tensor))`: A method that gets the variance of a tensor.
* `tf.math.reduce_std(tf.Tensor))`: A method that gets the standard deviation of a tensor.

In [ ]:
# start with a tensor with some negative values
E = tf.constant(
    np.random.randint(-100, 100, size=50)
)
E

In [ ]:
# find the aboslute value
tf.abs(E)

In [ ]:
# find the min value
tf.reduce_min(E)

In [ ]:
# find the max value
tf.reduce_max(E)

In [ ]:
# find the mean value
tf.reduce_mean(E)

In [ ]:
# find the aboslute value
tf.reduce_sum(E)

In [ ]:
# find the variance (must be float)
tf.math.reduce_variance(tf.cast(E, dtype=(tf.float32)))

In [ ]:
# find the std (must be float)
tf.math.reduce_std(tf.cast(E, dtype=(tf.float32)))

#  Positional Maximum and Minimum

* `tf.argmax(tf.Tensor)`: Find the position of value that's max in the tensor.
* `tf.argmin(tf.Tensor)`: Find the position of value that's min in the tensor.

In [ ]:
# create a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

In [ ]:
# find the positional max
tf.argmax(F)

In [ ]:
# check to see if the 42th value is indeed the max
tf.reduce_max(F) == F[tf.argmax(F)]

# Squeezing a Tensor

* `tf.squeeze(tf.Tensor)`: A method that removes dimensions of size 1.

In [ ]:
# start with a tensor
tf.random.set_seed(42)
G = tf.random.uniform([1, 1, 1, 1, 50])
G

In [ ]:
# squeeze a tensor
G_squeezed = tf.squeeze(G)
G_squeezed

# One-Hot Encoding Tensors

* `tf.one_hot(list, depth)`: A method that one-hot encodes a list of values.

In [ ]:
# create a list of indices
lst = [0, 1, 2, 3]

In [ ]:
# one-hot encode
tf.one_hot(lst, depth=4)

# Squaring, Log, Square-Root

* `tf.range(start, limit)`: Similar to np.arange.
* `tf.square(tf.Tensor)`: A method that sqaures each value within a tensor.
* `tf.sqrt(tf.Tensor)`: A method that takes the square-root of each value in a tensor. The dtype must not be int.
* `tf.math.log`: A method that takes the log of each value in a tensor.

In [ ]:
# get a tensor
H = tf.range(1, 10)
H

In [ ]:
# square each value
tf.square(H)

In [ ]:
# take square root of each value
tf.sqrt(tf.cast(H, dtype=tf.float32))

In [ ]:
# take log of each value
tf.math.log(tf.cast(H, dtype=tf.float32))

# Tensors & NumPy

In [ ]:
# create a tensor via a numpy array
H = tf.constant(np.array([3., 7., 10.]))
H

In [ ]:
# convert back to numpy array
np.array(H), type(np.array(H))

In [ ]:
# another way to convert
H.numpy(), type(H.numpy())

In [ ]:
# default type of tf vs np is different
np_J = tf.constant(np.array([3., 7., 10.]))
tf_J = tf.constant([3., 7., 10.])

np_J.dtype, tf_J.dtype

# Check GPU Usage

* `tf.config.list_physical_devices()`: Check to see if machine is running on CPU or GPU. For Google Colab, make sure GPU option is turned on.

In [ ]:
# check to see what devices are available on the machine
tf.config.list_physical_devices()

In [ ]:
# check to see if GPU is available
tf.config.list_physical_devices("GPU")

In [ ]:
# magic function to check nvidia GPU device
!nvidia-smi

# The `@tf.function` Decorator

In [ ]:
# create a simple function
def function(x, y):
    return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

In [ ]:
# create a tf.function using the decorator
@tf.function
def tf_function(x, y):
    return x ** 2 + y

tf_function(x, y)

In [ ]:
# check for equality
function(x, y) == tf_function(x, y)