<a href="https://colab.research.google.com/github/hiydavid/tfdev_learning/blob/main/ZTM/notebooks/tfdev_00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00: TensorFlow Fundamentals

In this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow. More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

# Creating Tensors with `tf.constant()`

* `tf.constant()`: A method that creates immutable tf.Tensor object. 
* `tf.dtypes`: A module for data types used in TensorFlow. A full list can be found [here](https://www.tensorflow.org/api_docs/python/tf/dtypes)
* `tf.Tensor.ndim`: An attribute that check the dimension of a tf.Tensor object.

In [78]:
# import libraries
import numpy as np

import tensorflow as tf
print(tf.__version__)

2.8.0


In [79]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [80]:
# check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [81]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [82]:
# check the dimension of vector
vector.ndim

1

In [83]:
# create a matrix
matrix = tf.constant(
    [[10, 7], 
     [7, 10]]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [84]:
# check the dimension of matrix
matrix.ndim

2

In [85]:
# create another matrix
another_matrix = tf.constant(
    [[10., 7.],
     [3. , 2.],
     [8. , 9.]],
     dtype=tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [86]:
# check the dimension of matrix
another_matrix.ndim

2

In [87]:
# create a tensor
tensor = tf.constant(
    [[[1, 2, 3],
      [4, 5, 6]],
     [[7, 8, 9],
      [10, 11, 12]],
     [[13, 14, 15],
      [16, 17, 18]]]
)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [88]:
# check tensor dimension
tensor.ndim

3

# Creating Tensors with `tf.Variable()`
* `tf.Variable()`: A method that creates mutable tf.Variable object
* `tf.Variable.assign()`: A method used to update a tf.Variable object.

In [89]:
# create the above tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [90]:
# try changing the changeable_tensor using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [91]:
# # now try changing the unchangeable_tensor using .assign()
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

# Creating Random Tensors

* `tf.random.Generator.from_seed(value)`: A class object that generate random numbers. The `from_seed()` method sets seed for reproducibility. Read about global seed vs. operation-level seed [here](https://www.tensorflow.org/api_docs/python/tf/random/set_seed).
* `tf.random.normal(shape=())`: A method that generates random numbers from a normal distribution. Other distribution can be found [here](https://www.tensorflow.org/api_docs/python/tf/random).
* `tf.random.shuffle(tf.Tensor)`: A method that takes a tf.Tensor object and shuffles the order along its first dimension.

In [92]:
# create two random tensors with the same seed
random_1 = tf.random.Generator.from_seed(42).normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3, 2))

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [93]:
# shuffle the order of the elements in a tensor
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]]
)

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [94]:
# shuffle with setting seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [95]:
# setting a global seed (now it no longer changes)
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Other Ways to Create Tensors

* `tf.ones(shape=())`: A method that creates a tensor with all 1s as elements.
* `tf.zeros(shape=())`: A method that creates a tensor with all 0s as elements.
* `tf.constant(np.arrange())`: Turn an numpy array into a tf.tensor.

In [96]:
# create a tensor of 1s
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [97]:
# create a tensor of all zeros
tf.zeros(shape=(9, 5))

<tf.Tensor: shape=(9, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [98]:
# create a tensor from numpy arrays
numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A)
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [99]:
# create a tensor from numpy arrays
B = tf.constant(numpy_A, shape=(2, 4, 3)) # shape must match array length
C = tf.constant(numpy_A, shape=(3, 8))

B, C

(<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

# Getting Information from Tensors

* `tf.Tensor.shape`: A method that gets the shape of a tf.Tensor object.
* `tf.Tensor.ndim`: A method that gets the rank of a tf.Tensor object.
* `tf.Tensor[0]`: A way to get a particular axis of a tf.Tensor object.
* `tf.size(tf.Tensor)`: A method to get the total number of items in a tf.Tensor object.

In [100]:
# create a rank 4 tensor
rank_4_tensor = tf.zeros([2, 3, 4, 5])
print("rank:", rank_4_tensor.ndim)
print("shape:", rank_4_tensor.shape)
print("size:", tf.size(rank_4_tensor).numpy())

rank: 4
shape: (2, 3, 4, 5)
size: 120


In [101]:
# other retreivable attributes of a tensor
print("datatype:", rank_4_tensor.dtype)
print("elements along the 0 axis:", rank_4_tensor.shape[0])
print("elements along last axis:", rank_4_tensor.shape[-1])

datatype: <dtype: 'float32'>
elements along the 0 axis: 2
elements along last axis: 5


# Indexing Tensors

* `[:, :, :]`: Similar to how numpy is indexed.
* `[..., ]`: A way to say include everything that came before it.
* `tf.newaxis`: A NoneType that can be used to add as new element into an existing tf.Ternsor.
* `tf.expand_dims(tf.Tensor, axis)`: A method to add a dimension to an existing tf.Tensor.

In [102]:
# get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [103]:
# get the first element from each dimension from each index except final
rank_4_tensor[:1, :1, :1, ]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [104]:
# get the last item of each row of our rank 2 tensor
rank_2_tensor = tf.constant(
    [[10, 7], 
     [3, 4]]
)

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [105]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [106]:
# alternative to using tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [107]:
# expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0) 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating Tensors

* `+, -, *, /`: Operators works with each element in a tf.Tensor.
* `tf.multiply(tf.Tensor, value)`: Same as using the `*` operator. 
* `tf.math`: The modules that contains many of the commonly used operators

In [108]:
# add values to a tensor using addition
tensor = tf.constant(
    [[10, 7], 
     [3, 4]]
)
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [109]:
# multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [110]:
# subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [111]:
# division
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [112]:
# we can use the tf built-in functions as well
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix Multiplication with Tensors

* `tf.matmult(tf.Tensor, tf.Tensor)`: Get dot product of two tf.Tensor objects.
* `@`: A python operator that's the same as tf.matmul.
* `tf.reshape(tf.Tensor, shape=())`: A method to transpose a tf.Tensor object. This is required to satisfy the matrix multiplication rule of matching inner dimensions of two different tensors.
* `tf.transpose(tf.Tensor)`: Also works, but this is flips the matrix by its diagonal axis, whereas reshape uses the same order but rebuilds the tensor into a new object.
* `tf.tensordot()`: This gets the dot product of two tf.Tensor objects. This method requires one of the two tf.Tensor objects to be transposed.
* Usually, transposing is the correct way in ML algorithms.

In [113]:
# matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [114]:
# matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [115]:
# element-wise matrix multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [116]:
# try with two tensors of different shapes
X = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6]]
)
Y = tf.constant(
    [[7, 8],
     [9, 10],
     [11, 12]]
)

# X @ Y # this gives you an error
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [117]:
# reshape also works too
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [118]:
# however, transpose and reshape yields different resuls
Y, tf.transpose(Y), tf.reshape(Y, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [119]:
# results are different
X @ tf.transpose(Y), X @ tf.reshape(Y, shape=(2, 3))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [120]:
# use tensordot
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

# Changing the Datatype of a Tensor

* `tf.Tensor.dtype`: An attribute that looksup a tensor's data type.
* `tf.cast(tf.Tensor, dtype=)`: A method that changes a tensor's dtype.
* Sometimes it is good to have mixed precision (float16 & float32). Read more [here](https://www.tensorflow.org/guide/mixed_precision).

In [121]:
# create a new tensor with default dtype (float32)
B = tf.constant(
    [1.7, 7.4]
)
B.dtype

tf.float32

In [122]:
# create a new tensor with default detype (int32)
C = tf.constant(
    [7, 10]
)
C.dtype

tf.int32

In [123]:
# change from float32 to float 16 (reducing precision)
D = tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

# Tensor Aggregation

* `tf.abs(tf.Tensor)`: A method that turns value into its absolute value.
* `tf.reduce_min(tf.Tensor)`: A method that gets the min value of a tensor.
* `tf.reduce_max(tf.Tensor)`: A method that gets the max value of a tensor.
* `tf.reduce_mean(tf.Tensor)`: A method that gets the mean of a tensor.
* `tf.reduce_sum(tf.Tensor)`: A method that gets the sum of a tensor.
* `tf.math.reduce_variance(tf.Tensor))`: A method that gets the variance of a tensor.
* `tf.math.reduce_std(tf.Tensor))`: A method that gets the standard deviation of a tensor.

In [124]:
# start with a tensor with some negative values
E = tf.constant(
    np.random.randint(-100, 100, size=50)
)
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([-16, -97,  71,  38, -79,  -4, -16,  60,  -5, -36, -37, -80, -33,
        50,  70,  62,  82, -92,  30, -17,  21,  36,  64,  20, -25, -99,
        95, -28, -64,  35,  38, -14, -38,  64, -73, -44, -41,  84, -93,
        69, -40,  49, -13, -93,  35, -11,  41, -91, -51, -72])>

In [125]:
# find the aboslute value
tf.abs(E)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([16, 97, 71, 38, 79,  4, 16, 60,  5, 36, 37, 80, 33, 50, 70, 62, 82,
       92, 30, 17, 21, 36, 64, 20, 25, 99, 95, 28, 64, 35, 38, 14, 38, 64,
       73, 44, 41, 84, 93, 69, 40, 49, 13, 93, 35, 11, 41, 91, 51, 72])>

In [126]:
# find the min value
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=-99>

In [127]:
# find the max value
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [128]:
# find the mean value
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=-5>

In [129]:
# find the aboslute value
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=-288>

In [134]:
# find the variance (must be float)
tf.math.reduce_variance(tf.cast(E, dtype=(tf.float32)))

<tf.Tensor: shape=(), dtype=float32, numpy=3253.9421>

In [133]:
# find the std (must be float)
tf.math.reduce_std(tf.cast(E, dtype=(tf.float32)))

<tf.Tensor: shape=(), dtype=float32, numpy=57.043335>

#  Positional Maximum and Minimum

* `tf.argmax(tf.Tensor)`: Find the position of value that's max in the tensor.
* `tf.argmin(tf.Tensor)`: Find the position of value that's min in the tensor.

In [135]:
# create a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [139]:
# find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [140]:
# check to see if the 42th value is indeed the max
tf.reduce_max(F) == F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a Tensor

* `tf.squeeze(tf.Tensor)`: A method that removes dimensions of size 1.

In [147]:
# start with a tensor
tf.random.set_seed(42)
G = tf.random.uniform([1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [149]:
# squeeze a tensor
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One-Hot Encoding Tensors

* `tf.one_hot(list, depth)`: A method that one-hot encodes a list of values.

In [150]:
# create a list of indices
lst = [0, 1, 2, 3]

In [151]:
# one-hot encode
tf.one_hot(lst, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Squaring, Log, Square-Root

* `tf.range(start, limit)`: Similar to np.arange.
* `tf.square(tf.Tensor)`: A method that sqaures each value within a tensor.
* `tf.sqrt(tf.Tensor)`: A method that takes the square-root of each value in a tensor. The dtype must not be int.
* `tf.math.log`: A method that takes the log of each value in a tensor.

In [152]:
# get a tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [153]:
# square each value
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [157]:
# take square root of each value
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [160]:
# take log of each value
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>