<a href="https://colab.research.google.com/github/hiydavid/tfdev_learning/blob/main/ZTM/exercises/tfdev_exercise_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 00: TensorfFlow Fundamentals

---

## 1) Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
# get libraries
import tensorflow as tf
import numpy as np

tf.__version__

'2.8.0'

In [ ]:
# 0 dimension scalar
scalar = tf.constant(0)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
# 1 dimension vector
vector = tf.constant([0, 0])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0], dtype=int32)>

In [ ]:
# 2 dimension matrix
matrix = tf.constant(
    [[0, 0],
     [0, 0],
     [0, 0]]
)
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [ ]:
# 3 dimension matrix
tensor = tf.constant(
    [[[0, 0, 0, 0],
      [0, 0, 0, 0]],
     [[0, 0, 0, 0],
      [0, 0, 0, 0]],
     [[0, 0, 0, 0],
      [0, 0, 0, 0]]]
)
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

---

## 2) Find the shape, rank and size of the tensors you created in 1.

In [ ]:
# get shape of scalar
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
# get shape of vector
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
# get shape of matrix
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([3, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [ ]:
# get shape of tensor
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([3, 2, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

---

## 3) Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
# first tensor
A = tf.random.uniform(
    shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.float32,
    seed=420
)
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.98712194, 0.59964657, 0.00641501, ..., 0.6114863 , 0.7519609 ,
        0.6864147 ],
       [0.6333941 , 0.63108015, 0.24132133, ..., 0.7785939 , 0.15714622,
        0.19466496],
       [0.4370383 , 0.66570103, 0.9755224 , ..., 0.66557145, 0.6570884 ,
        0.61052823],
       [0.36467457, 0.7055733 , 0.608951  , ..., 0.92137694, 0.81897676,
        0.07551825],
       [0.7980355 , 0.27227676, 0.8692752 , ..., 0.8022424 , 0.3373158 ,
        0.74890244]], dtype=float32)>

In [ ]:
# second tensor
B = tf.random.uniform(
    shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.float32,
    seed=69
)
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.8287811 , 0.7815381 , 0.97475886, ..., 0.79753804, 0.519063  ,
        0.59694827],
       [0.9909849 , 0.39044464, 0.65678334, ..., 0.8925388 , 0.02056515,
        0.0460937 ],
       [0.70839465, 0.20370603, 0.7863318 , ..., 0.89734316, 0.6024771 ,
        0.8938136 ],
       [0.6462165 , 0.44839513, 0.44885266, ..., 0.1800381 , 0.09376061,
        0.9511968 ],
       [0.10844648, 0.7448963 , 0.5729567 , ..., 0.84710145, 0.5456184 ,
        0.49527407]], dtype=float32)>

---

## 4) Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
# matmul
A @ tf.transpose(B)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.58289 , 68.91869 , 73.93973 , 69.02287 , 70.58133 ],
       [81.60768 , 80.130005, 80.75608 , 73.90163 , 78.14078 ],
       [76.86358 , 76.604004, 77.12991 , 70.3748  , 75.0512  ],
       [74.966415, 75.548744, 76.63756 , 68.08812 , 74.40893 ],
       [76.76872 , 73.45499 , 76.43706 , 70.2953  , 72.336975]],
      dtype=float32)>

---

## 5) Multiply the two tensors you created in 3 using dot product.

In [ ]:
# dot product
tf.tensordot(A, tf.transpose(B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.58289 , 68.91869 , 73.93973 , 69.02287 , 70.58133 ],
       [81.60768 , 80.130005, 80.75608 , 73.90163 , 78.14078 ],
       [76.86358 , 76.604004, 77.12991 , 70.3748  , 75.0512  ],
       [74.966415, 75.548744, 76.63756 , 68.08812 , 74.40893 ],
       [76.76872 , 73.45499 , 76.43706 , 70.2953  , 72.336975]],
      dtype=float32)>

---

## 6) Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
# create tensor
C = tf.random.normal([224, 224, 3])
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.23058935, -0.52180606, -0.51186645],
        [ 1.1094141 , -1.2420049 , -1.1994634 ],
        [-0.5238954 ,  0.13073859,  0.914823  ],
        ...,
        [ 0.19971247, -0.27307874,  1.4836743 ],
        [-0.8374113 ,  1.2210355 ,  0.67347974],
        [ 3.172484  , -1.0080316 , -2.1834915 ]],

       [[ 0.65937823, -0.06835774,  1.156886  ],
        [ 0.5496369 , -1.4345238 ,  1.4154229 ],
        [ 0.26294848,  0.40256345, -0.20043379],
        ...,
        [-0.93655854,  0.38368338, -2.307355  ],
        [-0.58011943,  0.61670923, -0.5926551 ],
        [ 1.0976962 ,  0.05451567,  0.9623117 ]],

       [[ 0.3595953 ,  0.23135038,  1.5760524 ],
        [ 1.4840802 , -0.30641845, -1.1658589 ],
        [-0.37783915, -1.4808862 , -0.83924204],
        ...,
        [ 1.0323775 ,  0.48421997, -1.8603761 ],
        [-0.01887878, -1.6726742 ,  1.3040602 ],
        [ 0.86701435, -0.05271871, -0.7298825 ]],

       ...,

     

---

## 7) Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
# find min
C_min_1axis = tf.math.reduce_min(C)
C_min_1axis

<tf.Tensor: shape=(), dtype=float32, numpy=-4.0690274>

In [ ]:
# find max
C_max_1axis = tf.math.reduce_max(C)
C_max_1axis

<tf.Tensor: shape=(), dtype=float32, numpy=4.298551>

---

## 8) Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
# create tensor
D = tf.random.normal([1, 224, 224, 3])
D.shape

TensorShape([1, 224, 224, 3])

In [ ]:
# same tensor unsqueezed
D_squeezed = tf.squeeze(D)
D_squeezed.shape

TensorShape([224, 224, 3])

---

## 9) Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
# create tensor
E = tf.random.normal([10])
E

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.8698235 , -0.32857704,  0.5025379 , -0.07065299, -0.8208469 ,
        2.6551487 ,  0.91829497, -0.7990526 , -0.6039011 , -0.45866677],
      dtype=float32)>

In [ ]:
# max value
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float32, numpy=2.6551487>

In [ ]:
# max value's position
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

---

## 10) One-hot encode the tensor you created in 9.

In [ ]:
# one-hot the above tensor
tf.one_hot(
    indices=tf.cast(E, dtype=tf.int32).numpy(),
    depth=tf.size(E).numpy()
)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>